curseTowerMod = RegisterMod("Curse Of The Tower", 1)
local savedata = require("curseofthetower_scripts.savedata")
-- savedata:preGameExit(willSave)
-- savedata:postGameStarted(isGameOver)
-- savedata:onPlayerInit()
-- savedata:onGameExit()
-- savedata:onGameEnd()

-- Files
local eid = require("curseofthetower_scripts.modcompatibility.eid")
local encyclopedia = require("curseofthetower_scripts.modcompatibility.encyclopedia")
local painKillers = require("curseofthetower_scripts.items.collectibles.painkillers")
local tarotBombs = require("curseofthetower_scripts.items.collectibles.tarotbombs")
local pokerFace = require("curseofthetower_scripts.items.collectibles.pokerface")
local mintyGum = require("curseofthetower_scripts.items.trinkets.mintygum")
local theUnexpected = require("curseofthetower_scripts.items.trinkets.theunexpected")
local popOmatic = require("curseofthetower_scripts.items.collectibles.popomatic")
local whiteBelt = require("curseofthetower_scripts.items.collectibles.whitebelt")
local freeBlood = require("curseofthetower_scripts.items.trinkets.freeblood")
local whoAmI = require("curseofthetower_scripts.items.pickups.whoami")
local kerosene = require("curseofthetower_scripts.items.collectibles.kerosene")
local iceCream = require("curseofthetower_scripts.items.collectibles.icecream")
local giftCard = require("curseofthetower_scripts.items.pickups.giftcard")
local rejectTech = require("curseofthetower_scripts.items.trinkets.rejecttech")
local darkOrb = require("curseofthetower_scripts.items.collectibles.darkorb")
local lilRainmaker = require("curseofthetower_scripts.items.collectibles.lilrainmaker")
local terrorporter = require("curseofthetower_scripts.items.collectibles.terrorporter")
local hexOfTheTower = require("curseofthetower_scripts.items.collectibles.hexofthetower")

-- Mod Compatibility Functions
eid:addEid()
encyclopedia:addEncyclopedia()